[workspace]
resolver = "3"
members = ["crates/moqros", "crates/moqros-cli", "examples/image_source"]
default-members = ["crates/moqros", "crates/moqros-cli", "examples/image_source"]

[workspace.package]
version = "0.2.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/yuma-m/moqros"
rust-version = "1.91"

[workspace.dependencies]
moqros = { path = "crates/moqros", version = "0.2.0" }
anyhow = "1"
bytes = "1"
clap = { version = "4", features = ["derive", "env"] }
futures = "0.3"
hang = "0.21.11"
moq-tokio = "0.19.23"
openh264 = { version = "0.9.8", default-features = false, features = ["libloading"] }
env-libvpx-sys = { version = "5.1.3", features = ["generate"] }
r2r = "0.9.7"
thiserror = "2"
tokio = { version = "1.47", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = "2"
